# pre-commit run --all-files
exclude: 'migrations/.*'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-added-large-files
        args: ['--maxkb=500']
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: [--target-version, py36]
        exclude: 'migrations/.*'
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.5
    hooks:
    -   id: ruff
        args: ['--fix']
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: ["--ignore", "E,W,F"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        exclude: 'migrations/.*'
-   repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.7
    hooks:
    - id: conventional-commits
